# Generated by Django 6.0.3 on 2026-04-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_customuser_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
