# Generated by Django 6.0.3 on 2026-04-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_offer_creator_offer_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='creator',
            new_name='creator_id',
        ),
    ]
