# Generated by Django 6.0.3 on 2026-04-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_rename_creator_offer_creator_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='creator_id',
            new_name='creator',
        ),
    ]
