# Generated by Django 6.0.3 on 2026-04-06 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_offer_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
