# Generated by Django 6.0.3 on 2026-04-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_time_in_days_order_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_time_in_days',
        ),
        migrations.RemoveField(
            model_name='order',
            name='features',
        ),
        migrations.RemoveField(
            model_name='order',
            name='offer_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='revisions',
        ),
        migrations.RemoveField(
            model_name='order',
            name='title',
        ),
    ]
