# Generated by Django 6.0.3 on 2026-04-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_delivery_time_in_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('in_progress', 'In_Progress'), ('completed', 'Completed')], default='in_progress', max_length=20),
        ),
    ]
